// Connection Cards — bundled static content for the card-stack modules.
// No text input, no server-side storage, no auth beyond existing match state,
// no monetization gating. Content ships in the app.

// ── Going Deeper — 55 cards, medium vulnerability (values, life-story) ──
export const GOING_DEEPER = [
  { en: `What value did your family teach you that you still carry?`, fr: `Quelle valeur votre famille vous a-t-elle enseignée et que vous portez encore ?` },
  { en: `What is a value you have chosen to let go of?`, fr: `Quelle valeur avez-vous choisie d'abandonner ?` },
  { en: `What does success mean to you now versus five years ago?`, fr: `Que signifie la réussite pour vous aujourd'hui vs il y a cinq ans ?` },
  { en: `Name a belief you inherited and later questioned.`, fr: `Nommez une croyance héritée puis remise en question.` },
  { en: `What part of your story are you most proud of?`, fr: `Quelle partie de votre histoire vous rend le/la plus fier(ère) ?` },
  { en: `What is a risk that shaped who you are?`, fr: `Quel risque a façonné qui vous êtes ?` },
  { en: `What did younger-you need that they did not get?`, fr: `De quoi le/la vous du passé avait-il/elle besoin sans l'obtenir ?` },
  { en: `What is a chapter you would rewrite, and why?`, fr: `Quel chapitre réécririez-vous, et pourquoi ?` },
  { en: `What role did silence play in your home growing up?`, fr: `Quel rôle jouait le silence dans votre foyer enfant ?` },
  { en: `What is a lesson you learned the hard way?`, fr: `Quelle leçon avez-vous apprise à vos dépens ?` },
  { en: `What does home mean to you?`, fr: `Que signifie le foyer pour vous ?` },
  { en: `What tradition do you want to keep or create?`, fr: `Quelle tradition voulez-vous garder ou créer ?` },
  { en: `What is a boundary you had to learn to set?`, fr: `Quelle limite avez-vous dû apprendre à poser ?` },
  { en: `What do you admire in your closest friend?`, fr: `Qu'admirez-vous chez votre ami(e) le/la plus proche ?` },
  { en: `What do you admire in yourself?`, fr: `Qu'admirez-vous chez vous ?` },
  { en: `What is a cause you would stand up for publicly?`, fr: `Quelle cause défendriez-vous publiquement ?` },
  { en: `What does generosity look like in your life?`, fr: `À quoi ressemble la générosité dans votre vie ?` },
  { en: `What is something you have changed your mind about?`, fr: `Quelle est une chose sur laquelle vous avez changé d'avis ?` },
  { en: `What does integrity ask of you right now?`, fr: `Que demande de vous l'intégrité en ce moment ?` },
  { en: `What is a story you tell about yourself that may not be true anymore?`, fr: `Quelle histoire racontez-vous sur vous qui n'est peut-être plus vraie ?` },
  { en: `What did you learn about love early on?`, fr: `Qu'avez-vous appris sur l'amour très tôt ?` },
  { en: `What did you learn about conflict early on?`, fr: `Qu'avez-vous appris sur le conflit très tôt ?` },
  { en: `What is a fear you have outgrown?`, fr: `Quelle peur avez-vous dépassée ?` },
  { en: `What is a fear still with you?`, fr: `Quelle peur est encore présente ?` },
  { en: `What place has shaped you most?`, fr: `Quel lieu vous a le/la plus façonné(e) ?` },
  { en: `What season of life are you in now?`, fr: `Dans quelle saison de vie êtes-vous maintenant ?` },
  { en: `What does rest mean to you?`, fr: `Que signifie le repos pour vous ?` },
  { en: `What is a small joy you would defend fiercely?`, fr: `Quelle petite joie défendriez-vous farouchement ?` },
  { en: `What is a regret that taught you something?`, fr: `Quel regret vous a appris quelque chose ?` },
  { en: `What kind of elder do you want to become?`, fr: `Quel/le aîné(e) voulez-vous devenir ?` },
  { en: `What is a promise you made to yourself?`, fr: `Quelle promesse vous êtes-vous faite ?` },
  { en: `What does forgiveness mean to you?`, fr: `Que signifie le pardon pour vous ?` },
  { en: `What is something you are still figuring out?`, fr: `Quelle est une chose que vous cherchez encore ?` },
  { en: `What did you have to unlearn?`, fr: `Qu'avez-vous dû désapprendre ?` },
  { en: `What is a moment you felt truly yourself?`, fr: `Quel est un moment où vous vous êtes senti(e) pleinement vous-même ?` },
  { en: `What do you want to be known for?`, fr: `Pour quoi voulez-vous être connu(e) ?` },
  { en: `What do you want to be forgiven for?`, fr: `De quoi voulez-vous être pardonné(e) ?` },
  { en: `What is a question you are living more than answering?`, fr: `Quelle question vivez-vous plus que vous n'y répondez ?` },
  { en: `What does belonging mean to you?`, fr: `Que signifie l'appartenance pour vous ?` },
  { en: `What is a gift you have that you undervalue?`, fr: `Quel don avez-vous que vous sous-estimez ?` },
  { en: `What is a wound that became wisdom?`, fr: `Quelle blessure est devenue sagesse ?` },
  { en: `What is a choice that took courage?`, fr: `Quel choix a demandé du courage ?` },
  { en: `What is a no you are glad you said?`, fr: `Quel non êtes-vous heureux/se d'avoir dit ?` },
  { en: `What is a yes that changed your path?`, fr: `Quel oui a changé votre chemin ?` },
  { en: `What do you want more time for?`, fr: `Pour quoi voulez-vous plus de temps ?` },
  { en: `What does enough look like for you?`, fr: `À quoi ressemble « assez » pour vous ?` },
  { en: `What is a part of your identity you are still making peace with?`, fr: `Quelle part de votre identité cherchez-vous encore à accepter ?` },
  { en: `What is a legacy you would like to leave?`, fr: `Quel héritage aimeriez-vous laisser ?` },
  { en: `What is a conversation you still need to have?`, fr: `Quelle conversation avez-vous encore besoin d'avoir ?` },
  { en: `What is a truth you avoid saying out loud?`, fr: `Quelle vérité évitez-vous de dire à voix haute ?` },
  { en: `What does trust cost you?`, fr: `Que vous coûte la confiance ?` },
  { en: `What is a season you are grateful for now?`, fr: `Quelle saison vous rend-elle reconnaissant(e) aujourd'hui ?` },
  { en: `What is a risk you are glad you did not take?`, fr: `Quel risque êtes-vous heureux/se de ne pas avoir pris ?` },
  { en: `What does curiosity ask of you today?`, fr: `Que demande de vous la curiosité aujourd'hui ?` },
  { en: `What part of your story is still being written?`, fr: `Quelle part de votre histoire s'écrit encore ?` },
];

// ── Deep Connection — 55 cards, high vulnerability (intimacy-building) ──
export const DEEP_CONNECTION = [
  { en: `When do you feel most seen?`, fr: `Quand vous sentez-vous le/la plus vu(e) ?` },
  { en: `What do you wish people knew about you without having to tell them?`, fr: `Que souhaitez-vous que les gens sachent de vous sans avoir à le dire ?` },
  { en: `What scares you most about being close to someone?`, fr: `Qu'est-ce qui vous effraie le plus dans la proximité ?` },
  { en: `What is a part of you that you rarely show?`, fr: `Quelle part de vous montrez-vous rarement ?` },
  { en: `When did you last feel truly held?`, fr: `Quand vous êtes-vous senti(e) vraiment porté(e) pour la dernière fois ?` },
  { en: `What is a longing you have not named yet?`, fr: `Quel désir n'avez-vous pas encore nommé ?` },
  { en: `What does tenderness mean to you?`, fr: `Que signifie la tendresse pour vous ?` },
  { en: `What is a memory of feeling safe?`, fr: `Quel est un souvenir où vous vous sentiez en sécurité ?` },
  { en: `What is a memory of feeling unseen?`, fr: `Quel est un souvenir où vous sentiez invisible ?` },
  { en: `What do you most want to be accepted for?`, fr: `Pour quoi voulez-vous le plus être accepté(e) ?` },
  { en: `What is a vulnerability you are proud of?`, fr: `Quelle vulnérabilité vous rend fier(ère) ?` },
  { en: `What is a wall you are ready to lower?`, fr: `Quel mur êtes-vous prêt(e) à abaisser ?` },
  { en: `What does being chosen mean to you?`, fr: `Que signifie être choisi(e) pour vous ?` },
  { en: `What does choosing someone mean to you?`, fr: `Que signifie choisir quelqu'un pour vous ?` },
  { en: `What is a fear you have about love?`, fr: `Quelle peur avez-vous concernant l'amour ?` },
  { en: `What is a hope you are afraid to say?`, fr: `Quel espoir avez-vous peur d'exprimer ?` },
  { en: `When do you feel most alive with another person?`, fr: `Quand vous sentez-vous le/la plus vivant(e) avec quelqu'un ?` },
  { en: `What is a part of your body or self you are making peace with?`, fr: `Quelle part de votre corps ou de vous acceptez-vous ?` },
  { en: `What is a secret you keep from yourself?`, fr: `Quel secret vous gardez-vous à vous-même ?` },
  { en: `What is a truth about your desires?`, fr: `Quelle est une vérité sur vos désirs ?` },
  { en: `What does intimacy mean to you beyond the physical?`, fr: `Que signifie l'intimité pour vous au-delà du physique ?` },
  { en: `What is a moment you wished someone had stayed?`, fr: `Quel est un moment où vous auriez voulu que l'autre reste ?` },
  { en: `What is a moment you are glad you stayed?`, fr: `Quel est un moment où vous êtes heureux/se d'être resté(e) ?` },
  { en: `What does it mean to you to be trusted?`, fr: `Que signifie pour vous être digne de confiance ?` },
  { en: `What is a wound you do not want passed on?`, fr: `Quelle blessure ne voulez-vous pas transmettre ?` },
  { en: `What is a joy you want to share more?`, fr: `Quelle joie voulez-vous partager davantage ?` },
  { en: `What is a grief you carry quietly?`, fr: `Quel chagrin portez-vous en silence ?` },
  { en: `What is something you want to be brave about?`, fr: `Quelle est une chose dont vous voulez être courageux/se ?` },
  { en: `What does surrender mean to you in love?`, fr: `Que signifie l'abandon dans l'amour pour vous ?` },
  { en: `What does commitment mean to you?`, fr: `Que signifie l'engagement pour vous ?` },
  { en: `What is a promise you want to keep?`, fr: `Quelle promesse voulez-vous tenir ?` },
  { en: `What is a limit you want respected?`, fr: `Quelle limite voulez-vous voir respectée ?` },
  { en: `What does repair look like for you after hurt?`, fr: `À quoi ressemble la réparation après une blessure pour vous ?` },
  { en: `What is a part of you that needs reassurance?`, fr: `Quelle part de vous a besoin de réassurance ?` },
  { en: `What is a part of you that is stronger than you think?`, fr: `Quelle part de vous est plus forte que vous ne le pensez ?` },
  { en: `What does it mean to let someone in?`, fr: `Que signifie laisser quelqu'un entrer ?` },
  { en: `What does it mean to let someone go?`, fr: `Que signifie laisser quelqu'un partir ?` },
  { en: `What is a feeling you are afraid will overwhelm you?`, fr: `Quel ressenti craignez-vous qui vous submerge ?` },
  { en: `What is a feeling you are learning to welcome?`, fr: `Quel ressenti apprenez-vous à accueillir ?` },
  { en: `What is a truth about your capacity to love?`, fr: `Quelle est une vérité sur votre capacité à aimer ?` },
  { en: `What is a truth about your capacity to be loved?`, fr: `Quelle est une vérité sur votre capacité à être aimé(e) ?` },
  { en: `What is a moment you felt brave in love?`, fr: `Quel est un moment où vous avez été courageux/se en amour ?` },
  { en: `What is a moment you felt small in love?`, fr: `Quel est un moment où vous vous êtes senti(e) petit(e) en amour ?` },
  { en: `What does devotion mean to you?`, fr: `Que signifie la dévotion pour vous ?` },
  { en: `What does fidelity mean to you?`, fr: `Que signifie la fidélité pour vous ?` },
  { en: `What is a dream you hold for your relationships?`, fr: `Quel rêve portez-vous pour vos relations ?` },
  { en: `What is a fear you have about being known?`, fr: `Quelle peur avez-vous d'être connu(e) ?` },
  { en: `What is a hope you have about being known?`, fr: `Quel espoir avez-vous d'être connu(e) ?` },
  { en: `What does it mean to grow with someone?`, fr: `Que signifie grandir avec quelqu'un ?` },
  { en: `What does it mean to grow apart?`, fr: `Que signifie grandir séparément ?` },
  { en: `What is a part of your heart you are protecting?`, fr: `Quelle part de votre cœur protégez-vous ?` },
  { en: `What is a part of your heart you are opening?`, fr: `Quelle part de votre cœur ouvrez-vous ?` },
  { en: `What is a question you want to ask but have not?`, fr: `Quelle question voulez-vous poser sans l'avoir faite ?` },
  { en: `What is an answer you are not ready to give?`, fr: `Quelle réponse n'êtes-vous pas prêt(e) à donner ?` },
  { en: `What does it mean to you to say I trust you?`, fr: `Que signifie pour vous dire je te fais confiance ?` },
  { en: `What does it mean to you to say I am here?`, fr: `Que signifie pour vous dire je suis là ?` },
];

// Soft pacing gate for Deep Connection (NOT a payment gate).
export const DEEP_CONNECTION_GATE = {
  title_en: `Ready to go deeper?`,
  title_fr: `Prêt(e) à aller plus loin ?`,
  body_en: `These prompts invite real vulnerability. There is no pressure and no cost, only your timing. Open one whenever you feel ready.`,
  body_fr: `Ces invites appellent une vraie vulnérabilité. Aucune pression, aucun coût, seulement votre rythme. Ouvrez-les quand vous le sentez.`,
  cta_en: `I am ready`,
  cta_fr: `Je suis prêt(e)`,
};

// ── Couples Mode — capitalization (share good news, partner responds with curiosity) ──
export const COUPLES_CAPITALIZATION = [
  { en: `Share one good thing from your day. Partner, ask what made it feel good.`, fr: `Partagez une bonne chose de votre journée. Partenaire, demandez ce qui l'a rendue agréable.` },
  { en: `Share a small win from this week. Partner, ask what part you are most proud of.`, fr: `Partagez une petite victoire de la semaine. Partenaire, demandez dont vous êtes le/la plus fier(ère).` },
  { en: `Share something you are looking forward to. Partner, ask what excites you most about it.`, fr: `Partagez ce que vous attendez avec impatience. Partenaire, demandez ce qui vous enthousiasme le plus.` },
  { en: `Share a kind moment someone offered you. Partner, ask how it felt to receive it.`, fr: `Partagez un moment de gentillesse reçu. Partenaire, demandez comment cela s'est senti.` },
  { en: `Share something you did well today. Partner, ask what made it possible.`, fr: `Partagez quelque chose que vous avez bien fait aujourd'hui. Partenaire, demandez ce qui l'a rendu possible.` },
  { en: `Share a moment you felt like yourself. Partner, ask what brought that out.`, fr: `Partagez un moment où vous étiez vous-même. Partenaire, demandez ce qui l'a fait émerger.` },
  { en: `Share a surprise that pleased you. Partner, ask what you will remember about it.`, fr: `Partagez une surprise agréable. Partenaire, demandez ce que vous en retiendrez.` },
  { en: `Share a goal you are making progress on. Partner, ask what the next step is.`, fr: `Partagez un objectif en progrès. Partenaire, demandez quelle est la prochaine étape.` },
  { en: `Share a skill you are gaining. Partner, ask what you are enjoying about it.`, fr: `Partagez une compétence que vous acquérez. Partenaire, demandez ce qui vous plaît.` },
  { en: `Share a moment of beauty you noticed. Partner, ask what stopped you.`, fr: `Partagez un moment de beauté remarqué. Partenaire, demandez ce qui vous a arrêté(e).` },
  { en: `Share a compliment you received. Partner, ask how it landed.`, fr: `Partagez un compliment reçu. Partenaire, demandez comment il a été reçu.` },
  { en: `Share a connection you made with someone. Partner, ask what drew you to them.`, fr: `Partagez un lien créé avec quelqu'un. Partenaire, demandez ce qui vous a attiré(e).` },
  { en: `Share a risk that went well. Partner, ask what you learned.`, fr: `Partagez un risque qui a réussi. Partenaire, demandez ce que vous avez appris.` },
  { en: `Share a peaceful moment today. Partner, ask what helped you feel calm.`, fr: `Partagez un moment de paix aujourd'hui. Partenaire, demandez ce qui a aidé.` },
  { en: `Share a creative impulse you followed. Partner, ask where it led.`, fr: `Partagez un élan créatif suivi. Partenaire, demandez où il vous a mené.` },
  { en: `Share a good decision you made. Partner, ask what you would tell your past self.`, fr: `Partagez une bonne décision. Partenaire, demandez ce que vous diriez au/à la vous du passé.` },
  { en: `Share a laugh you had today. Partner, ask what made it funny.`, fr: `Partagez un rire aujourd'hui. Partenaire, demandez ce qui l'a rendu drôle.` },
  { en: `Share a moment you felt grateful for your body. Partner, ask what it let you do.`, fr: `Partagez un moment de gratitude pour votre corps. Partenaire, demandez ce qu'il vous a permis.` },
  { en: `Share a kindness you offered. Partner, ask how it felt to give it.`, fr: `Partagez une gentillesse offerte. Partenaire, demandez ce que donner a fait.` },
  { en: `Share a hope that grew today. Partner, ask what fed it.`, fr: `Partagez un espoir qui a grandi. Partenaire, demandez ce qui l'a nourri.` },
];

// ── Couples Mode — gratitude ──
export const COUPLES_GRATITUDE = [
  { en: `Name one thing your partner did this week that you are grateful for.`, fr: `Nommez une chose que votre partenaire a faite cette semaine et dont vous êtes reconnaissant(e).` },
  { en: `Tell your partner one quality you appreciate in them.`, fr: `Dites à votre partenaire une qualité que vous appréciez.` },
  { en: `Recall a hard moment your partner helped you through.`, fr: `Rappelez un moment difficile que votre partenaire vous a aidé(e) à traverser.` },
  { en: `Name a small daily habit of your partner you would miss if gone.`, fr: `Nommez une petite habitude de votre partenaire qui vous manquerait.` },
  { en: `Thank your partner for something they rarely get credit for.`, fr: `Remerciez votre partenaire pour quelque chose rarement reconnu.` },
  { en: `Name a way your partner has grown that you admire.`, fr: `Nommez une façon dont votre partenaire a grandi que vous admirez.` },
  { en: `Recall a time your partner showed patience with you.`, fr: `Rappelez un moment où votre partenaire a fait preuve de patience.` },
  { en: `Name a way your partner makes home feel like home.`, fr: `Nommez une façon dont votre partenaire rend le foyer accueillant.` },
  { en: `Thank your partner for a kindness from early in your relationship.`, fr: `Remerciez votre partenaire pour une gentillesse du début de votre relation.` },
  { en: `Name a strength your partner brings to challenges.`, fr: `Nommez une force que votre partenaire apporte aux difficultés.` },
  { en: `Recall a laugh you shared that still warms you.`, fr: `Rappelez un rire partagé qui vous réchauffe encore.` },
  { en: `Name something your partner does that makes you feel cared for.`, fr: `Nommez quelque chose que votre partenaire fait et qui vous fait sentir choyé(e).` },
  { en: `Thank your partner for staying during a hard season.`, fr: `Remerciez votre partenaire d'être resté(e) durant une saison difficile.` },
  { en: `Name a way your partner has believed in you.`, fr: `Nommez une façon dont votre partenaire a cru en vous.` },
  { en: `Recall a moment your partner chose you.`, fr: `Rappelez un moment où votre partenaire vous a choisi(e).` },
  { en: `Name a way your partner supports your growth.`, fr: `Nommez une façon dont votre partenaire soutient votre croissance.` },
  { en: `Thank your partner for a small thing from today.`, fr: `Remerciez votre partenaire pour une petite chose d'aujourd'hui.` },
  { en: `Name a quality in your partner you hope to learn.`, fr: `Nommez une qualité de votre partenaire que vous espérez apprendre.` },
  { en: `Recall a time your partner made you feel safe.`, fr: `Rappelez un moment où votre partenaire vous a mis(e) en sécurité.` },
  { en: `Name a reason you are glad you are together.`, fr: `Nommez une raison dont vous êtes heureux/se d'être ensemble.` },
];

// ── Couples Mode — shared future / novelty ──
export const COUPLES_SHARED_FUTURE = [
  { en: `Imagine a year from now: what do you hope we are celebrating?`, fr: `Imaginez dans un an : que célébrerons-nous, espérez-vous ?` },
  { en: `What is one new experience you would like us to try together?`, fr: `Quelle nouvelle expérience aimeriez-vous essayer ensemble ?` },
  { en: `What is a place you would like us to visit as a couple?`, fr: `Quel lieu aimeriez-vous visiter ensemble ?` },
  { en: `What is a tradition we could start this year?`, fr: `Quelle tradition pourrions-nous commencer cette année ?` },
  { en: `What is a skill we could learn together?`, fr: `Quelle compétence pourrions-nous apprendre ensemble ?` },
  { en: `What is a small adventure we could plan this month?`, fr: `Quelle petite aventure pourrions-nous planifier ce mois-ci ?` },
  { en: `What is a dream we have talked about but not pursued?`, fr: `Quel rêve avons-nous évoqué sans le poursuivre ?` },
  { en: `What is a way we could surprise each other this week?`, fr: `Comment pourrions-nous nous surprendre cette semaine ?` },
  { en: `What is a goal we could set as a team?`, fr: `Quel objectif pourrions-nous fixer en équipe ?` },
  { en: `What is a way we could play more together?`, fr: `Comment pourrions-nous jouer plus ensemble ?` },
  { en: `What is a habit we could build together for our wellbeing?`, fr: `Quelle habitude bâtir ensemble pour notre bien-être ?` },
  { en: `What is a place in our home we could make ours?`, fr: `Quel lieu de notre maison pourrions-nous rendre nôtre ?` },
  { en: `What is a way we could mark the seasons together?`, fr: `Comment pourrions-nous marquer les saisons ensemble ?` },
  { en: `What is a conversation about our future we have not had yet?`, fr: `Quelle conversation sur notre avenir n'avons-nous pas encore eue ?` },
  { en: `What is a way we could support each other's dreams this year?`, fr: `Comment soutenir nos rêves respectifs cette année ?` },
  { en: `What is a small ritual we could protect from busy weeks?`, fr: `Quel petit rituel protéger des semaines chargées ?` },
  { en: `What is a way we could give back together?`, fr: `Comment pourrions-nous rendre ensemble ?` },
  { en: `What is a way we could rest together more intentionally?`, fr: `Comment nous reposer ensemble plus intentionnellement ?` },
  { en: `What is a way we could celebrate us, just because?`, fr: `Comment célébrer notre couple, sans raison ?` },
  { en: `What is a future you are excited to build with me?`, fr: `Quel avenir êtes-vous enthousiaste de bâtir avec moi ?` },
];